using SyntheticDataGenerator.Models;

namespace SyntheticDataGenerator.Services;

public class DependencyGraph
{
    private readonly Dictionary<string, HashSet<string>> _adjacency = new();
    private readonly Dictionary<string, int> _inDegree = new();
    private readonly Dictionary<string, TableInfo> _tableMap = new();
    private readonly HashSet<string> _selfReferencingTables = new();

    public IReadOnlySet<string> SelfReferencingTables => _selfReferencingTables;

    public void Build(
        List<TableInfo> tables,
        Dictionary<string, HashSet<string>>? columnsInScope = null)
    {
        foreach (var table in tables)
        {
            var name = table.FullName;
            _tableMap[name] = table;
            _adjacency.TryAdd(name, []);
            _inDegree.TryAdd(name, 0);
        }

        foreach (var table in tables)
        {
            foreach (var fk in table.ForeignKeys)
            {
                if (fk.IsSelfReferencing)
                {
                    _selfReferencingTables.Add(table.FullName);
                    continue;
                }

                if (columnsInScope is not null
                    && columnsInScope.TryGetValue(table.FullName, out var scopedCols)
                    && !scopedCols.Contains(fk.ParentColumn))
                    continue;

                var from = fk.FullReferencedTableName;
                var to = fk.FullParentTableName;

                if (!_adjacency.ContainsKey(from) || !_adjacency.ContainsKey(to))
                    continue;

                if (_adjacency[from].Add(to))
                    _inDegree[to]++;
            }
        }
    }

    /// <summary>
    /// Adds directed edges for custom (business-logic) column dependencies.
    /// The source column is whichever <see cref="CustomColumnRef"/> the validator
    /// flagged with <see cref="CustomColumnRef.IsSource"/> (chosen via the
    /// External &gt; PrimaryKey &gt; AutoGenerated &gt; Unique &gt; first-declared
    /// cascade). External-root sources don't appear in the graph and impose no
    /// ordering on their dependents.
    /// </summary>
    public void AddCustomDependencies(List<CustomDependencyGroup>? groups)
    {
        if (groups is null or { Count: 0 })
            return;

        foreach (var group in groups)
        {
            if (group.Columns.Count < 2)
                continue;

            var sourceRef = group.Columns.FirstOrDefault(c => c.IsSource)
                            ?? group.Columns[0];

            if (sourceRef.IsExternalRoot)
                continue;

            var sourceTable = sourceRef.Table;
            if (!_adjacency.ContainsKey(sourceTable))
                continue;

            foreach (var dep in group.Columns)
            {
                if (ReferenceEquals(dep, sourceRef))
                    continue;
                if (!_adjacency.ContainsKey(dep.Table))
                    continue;
                if (string.Equals(sourceTable, dep.Table, StringComparison.OrdinalIgnoreCase))
                    continue;

                if (_adjacency[sourceTable].Add(dep.Table))
                    _inDegree[dep.Table]++;
            }
        }
    }

    /// <summary>
    /// Returns tables in topological order using Kahn's algorithm.
    /// Tables with no FK dependencies come first.
    /// </summary>
    public List<TableInfo> GetTopologicalOrder()
    {
        var inDegree = new Dictionary<string, int>(_inDegree);
        var queue = new Queue<string>();

        foreach (var (node, degree) in inDegree)
        {
            if (degree == 0)
                queue.Enqueue(node);
        }

        var sorted = new List<TableInfo>();

        while (queue.Count > 0)
        {
            var current = queue.Dequeue();
            sorted.Add(_tableMap[current]);

            if (!_adjacency.TryGetValue(current, out var neighbors))
                continue;

            foreach (var neighbor in neighbors)
            {
                inDegree[neighbor]--;
                if (inDegree[neighbor] == 0)
                    queue.Enqueue(neighbor);
            }
        }

        if (sorted.Count != _tableMap.Count)
        {
            var cycleNodes = _tableMap.Keys
                .Except(sorted.Select(t => t.FullName))
                .ToList();

            throw new InvalidOperationException(
                $"Circular FK dependency detected among tables: {string.Join(", ", cycleNodes)}. " +
                "Cannot determine a valid insertion order.");
        }

        return sorted;
    }
}
