using YamlDotNet.Serialization;

namespace SyntheticDataGenerator.Models;

public class GenerationPlan
{
    [YamlMember(Alias = "mode")]
    public string Mode { get; set; } = "insert";

    [YamlMember(Alias = "seed")]
    public int? Seed { get; set; }

    [YamlMember(Alias = "locale")]
    public string Locale { get; set; } = "en";

    [YamlMember(Alias = "tables")]
    public List<TablePlan> Tables { get; set; } = [];

    [YamlMember(Alias = "externalDependencies")]
    public List<ExternalDependency>? ExternalDependencies { get; set; }

    [YamlMember(Alias = "customDependencies")]
    public List<CustomDependencyGroup>? CustomDependencies { get; set; }
}

public class TablePlan
{
    [YamlMember(Alias = "table")]
    public string Table { get; set; } = string.Empty;

    [YamlMember(Alias = "order")]
    public int Order { get; set; }

    [YamlMember(Alias = "rowCount")]
    public int RowCount { get; set; } = 100;

    [YamlMember(Alias = "columns")]
    public List<ColumnPlan> Columns { get; set; } = [];

    [YamlMember(Alias = "uniqueConstraints")]
    public List<UniqueConstraintPlan>? UniqueConstraints { get; set; }

    [YamlIgnore]
    public string FullName => Table;

    [YamlIgnore]
    public string Schema => Table.Contains('.') ? Table[..Table.IndexOf('.')] : string.Empty;

    [YamlIgnore]
    public string TableName => Table.Contains('.') ? Table[(Table.IndexOf('.') + 1)..] : Table;
}

public class UniqueConstraintPlan
{
    [YamlMember(Alias = "name")]
    public string Name { get; set; } = string.Empty;

    [YamlMember(Alias = "columns")]
    public List<string> Columns { get; set; } = [];

    [YamlMember(Alias = "filterDefinition")]
    public string? FilterDefinition { get; set; }
}

public class ExternalDependency
{
    [YamlMember(Alias = "fkName")]
    public string FkName { get; set; } = string.Empty;

    /// <summary>
    /// "outbound" = scoped table FK references external table.
    /// "inbound"  = external table FK references scoped table.
    /// </summary>
    [YamlMember(Alias = "direction")]
    public string Direction { get; set; } = string.Empty;

    [YamlMember(Alias = "scopedTable")]
    public string ScopedTable { get; set; } = string.Empty;

    [YamlMember(Alias = "scopedColumn")]
    public string ScopedColumn { get; set; } = string.Empty;

    [YamlMember(Alias = "externalTable")]
    public string ExternalTable { get; set; } = string.Empty;

    [YamlMember(Alias = "externalColumn")]
    public string ExternalColumn { get; set; } = string.Empty;
}

public class CustomDependencyGroup
{
    [YamlMember(Alias = "columns")]
    public List<CustomColumnRef> Columns { get; set; } = [];
}

public class CustomColumnRef
{
    [YamlMember(Alias = "table")]
    public string Table { get; set; } = string.Empty;

    [YamlMember(Alias = "column")]
    public string Column { get; set; } = string.Empty;

    /// <summary>
    /// True when this column lives outside TablesToInclude (either the whole
    /// table is excluded, or the column is excluded from a scoped table's
    /// Columns filter). Such columns become virtual roots — never generated;
    /// values are streamed from the live database at execution time.
    /// At most one column per CustomDependencyGroup may be flagged external.
    /// </summary>
    [YamlMember(Alias = "isExternalRoot")]
    public bool IsExternalRoot { get; set; }

    public bool ShouldSerializeIsExternalRoot() => IsExternalRoot;

    /// <summary>
    /// True when this column was chosen as the source of its CustomDependencyGroup
    /// by the validator's source-resolution cascade
    /// (External > PrimaryKey > AutoGenerated > Unique > first declared).
    /// Exactly one column per group is the source; all others copy values from it.
    /// </summary>
    [YamlMember(Alias = "isSource")]
    public bool IsSource { get; set; }

    public bool ShouldSerializeIsSource() => IsSource;

    /// <summary>
    /// When set, this column's values come from a flat values file (one value
    /// per line) instead of being streamed from the live database. Only
    /// meaningful when <see cref="IsExternalRoot"/> is also true — it backs the
    /// external root's data source. Path may be absolute or relative; relative
    /// paths are resolved against the plan file's directory at runtime.
    /// </summary>
    [YamlMember(Alias = "valuesFile")]
    public string? ValuesFile { get; set; }

    public bool ShouldSerializeValuesFile() => !string.IsNullOrEmpty(ValuesFile);

    /// <summary>
    /// Inline list of values supplied via CustomValueLists. Carried by the
    /// validator from <see cref="CustomValueList.Values"/> down to the plan
    /// emitter, which embeds it in the dependent columns' generatorArgs as
    /// <c>values: [...]</c>. Mutually exclusive with <see cref="ValuesFile"/>.
    /// Not normally serialized on the CustomColumnRef itself — the
    /// <c>ShouldSerialize</c> guard keeps it out of any incidental round-trip.
    /// </summary>
    [YamlMember(Alias = "values")]
    public List<string>? Values { get; set; }

    public bool ShouldSerializeValues() => Values is { Count: > 0 };
}

public class ColumnPlan : IColumnMetadata
{
    [YamlMember(Alias = "name")]
    public string Name { get; set; } = string.Empty;

    [YamlMember(Alias = "sqlType")]
    public string SqlType { get; set; } = string.Empty;

    [YamlMember(Alias = "maxLength")]
    public int MaxLength { get; set; }

    [YamlMember(Alias = "precision")]
    public byte Precision { get; set; }

    [YamlMember(Alias = "scale")]
    public byte Scale { get; set; }

    [YamlMember(Alias = "isNullable")]
    public bool IsNullable { get; set; }

    [YamlMember(Alias = "isIdentity")]
    public bool IsIdentity { get; set; }

    [YamlMember(Alias = "isPrimaryKey")]
    public bool IsPrimaryKey { get; set; }

    [YamlMember(Alias = "isComputed")]
    public bool IsComputed { get; set; }

    [YamlMember(Alias = "isRowVersion")]
    public bool IsRowVersion { get; set; }

    [YamlMember(Alias = "hasDefault")]
    public bool HasDefault { get; set; }

    [YamlMember(Alias = "isSequenceDefault")]
    public bool IsSequenceDefault { get; set; }

    [YamlMember(Alias = "isUnique")]
    public bool IsUnique { get; set; }

    [YamlMember(Alias = "generator")]
    public string Generator { get; set; } = string.Empty;

    [YamlMember(Alias = "generatorArgs")]
    public Dictionary<string, object?> GeneratorArgs { get; set; } = new();

    public bool ShouldSerializeGeneratorArgs() => GeneratorArgs is { Count: > 0 };

    [YamlMember(Alias = "valuesFile")]
    public string? ValuesFile { get; set; }
}
